/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "SIB1"
 * 	found in "SIB1.asn1"
 * 	`asn1c -gen-PER`
 */

#ifndef	_CellAccessRelatedInfo_H_
#define	_CellAccessRelatedInfo_H_


#include <asn_application.h>

/* Including external dependencies */
#include "PLMN-IdentityInfoList.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* CellAccessRelatedInfo */
typedef struct CellAccessRelatedInfo {
	PLMN_IdentityInfoList_t	 plmn_IdentityInfoList;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} CellAccessRelatedInfo_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_CellAccessRelatedInfo;

#ifdef __cplusplus
}
#endif

#endif	/* _CellAccessRelatedInfo_H_ */
#include <asn_internal.h>
