/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "SIB1"
 * 	found in "SIB1.asn1"
 * 	`asn1c -gen-PER`
 */

#ifndef	_PLMN_IdentityInfoList_H_
#define	_PLMN_IdentityInfoList_H_


#include <asn_application.h>

/* Including external dependencies */
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct PLMN_IdentityInfo;

/* PLMN-IdentityInfoList */
typedef struct PLMN_IdentityInfoList {
	A_SEQUENCE_OF(struct PLMN_IdentityInfo) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} PLMN_IdentityInfoList_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_PLMN_IdentityInfoList;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "PLMN-IdentityInfo.h"

#endif	/* _PLMN_IdentityInfoList_H_ */
#include <asn_internal.h>
