/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "SIB1"
 * 	found in "SIB1.asn1"
 * 	`asn1c -gen-PER`
 */

#ifndef	_PLMN_IdentityInfo_H_
#define	_PLMN_IdentityInfo_H_


#include <asn_application.h>

/* Including external dependencies */
#include "CellIdentity.h"
#include <NativeEnumerated.h>
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum cellReservedForOperatorUse {
	cellReservedForOperatorUse_reserved	= 0,
	cellReservedForOperatorUse_notReserved	= 1
} e_cellReservedForOperatorUse;

/* Forward declarations */
struct PLMN_Identity;

/* PLMN-IdentityInfo */
typedef struct PLMN_IdentityInfo {
	struct plmn_IdentityList {
		A_SEQUENCE_OF(struct PLMN_Identity) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} plmn_IdentityList;
	CellIdentity_t	 cellIdentity;
	long	 cellReservedForOperatorUse;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} PLMN_IdentityInfo_t;

/* Implementation */
/* extern asn_TYPE_descriptor_t asn_DEF_cellReservedForOperatorUse_5;	// (Use -fall-defs-global to expose) */
extern asn_TYPE_descriptor_t asn_DEF_PLMN_IdentityInfo;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "PLMN-Identity.h"

#endif	/* _PLMN_IdentityInfo_H_ */
#include <asn_internal.h>
