/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "SIB1"
 * 	found in "SIB1.asn1"
 * 	`asn1c -gen-PER`
 */

#ifndef	_SIB1_H_
#define	_SIB1_H_


#include <asn_application.h>

/* Including external dependencies */
#include "CellAccessRelatedInfo.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* SIB1 */
typedef struct SIB1 {
	CellAccessRelatedInfo_t	 cellAccessRelatedInfo;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SIB1_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SIB1;

#ifdef __cplusplus
}
#endif

#endif	/* _SIB1_H_ */
#include <asn_internal.h>
