function cellAccessRelatedInfo = getcellAccessRelatedInfo(                 ...
   mcc,                    ...
   mnc                     ...
    )

cellAccessRelatedInfo = getPLMN_IdentityInfoList(mcc,mnc);
  
end